---
name: Build

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheels for ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04, macos-11]
      fail-fast: false

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up QEMU
        if: runner.os == 'Linux'
        uses: docker/setup-qemu-action@v2
        with:
          platforms: all

      # Used to host cibuildwheel
      - uses: actions/setup-python@v3

      - name: Install cibuildwheel
        run: python -m pip install cibuildwheel==2.11.2

      - name: Build wheels
        run: python -m cibuildwheel --output-dir wheelhouse uwsgi
        env:
          CIBW_ARCHS_LINUX: auto aarch64
          CIBW_ARCHS_MACOS: x86_64
          # cross-compile for arm64 on macos isn't working yet
          # https://github.com/lincolnloop/pyuwsgi-wheels/issues/18
          # CIBW_ARCHS_MACOS: x86_64 arm64
          # tesing on emulated arm64 isn't supported for MacOS
          # CIBW_TEST_SKIP: "*-macosx_arm64"
          CIBW_SKIP: cp36-* pp*
          CIBW_ENVIRONMENT: APPEND_VERSION="" UWSGI_PROFILE=pyuwsginossl
          CIBW_TEST_COMMAND: pyuwsgi --help
          CIBW_BEFORE_ALL: ./patch-uwsgi-packaging.sh uwsgi
          CIBW_BEFORE_BUILD_MACOS: IS_MACOS=1 ./pre_build.sh
          CIBW_BEFORE_BUILD_LINUX: ./pre_build.sh && (yum install -y zlib-devel || apk add zlib-dev)

      - uses: actions/upload-artifact@v3
        with:
          path: ./wheelhouse/*.whl
