---
name: Build

on:
  push:
    branches: [main, test-me-*]
    tags: '*'
  pull_request:

jobs:
  build_sdist:
    name: Build sdist
    runs-on: ubuntu-latest
    outputs:
      sdist_name: ${{ steps.build_sdist.outputs.sdist_name }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true

      - name: Build sdist
        id: build_sdist
        run: |
          make sdist
          echo "sdist_name=pyuwsgi-$(bin/package-version)" >> "$GITHUB_OUTPUT"

      - uses: actions/upload-artifact@v4
        with:
          name: dist-sdist
          path: dist

      - uses: actions/upload-artifact@v4
        with:
          name: pre_build
          path: pre_build.sh

  build_wheels:
    name: Build wheels for ${{ matrix.os }} ${{ matrix.arch }}
    needs: [build_sdist]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
        #- {os: ubuntu-latest, arch: aarch64}
        #- {os: ubuntu-latest, arch: i686}
        - {os: ubuntu-latest, arch: x86_64}
        - {os: macos-13, arch: x86_64}
        - {os: macos-14, arch: arm64}
      fail-fast: false

    steps:

      - uses: actions/download-artifact@v4
        with:
          name: dist-sdist
          path: dist

      - uses: actions/download-artifact@v4
        with:
          name: pre_build
          path: .

      - name: Unpack sdist
        run: |
          tar -xvzf "dist/${{ needs.build_sdist.outputs.sdist_name }}.tar.gz"
          rm -rf dist
          chmod +x pre_build.sh

      - name: Set up QEMU
        if: matrix.arch == 'aarch64'
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all

      - name: avoid homebrew pcre2
        if: matrix.os == 'macos-14'
        run: brew unlink pcre2

      - name: install deps from homebrew for x86_64
        if: ${{ matrix.os == 'macos-13' && matrix.arch == 'x86_64'}}
        shell: bash
        run: |
          brew install pipx
        #brew install zeromq jansson pcre pipx

      - name: install deps from homebrew for arm64
        if: ${{ matrix.os == 'macos-14' && matrix.arch == 'arm64'}}
        shell: bash
        run: |
          brew install autoconf libtool automake

      #- name: setup Ccache
      #  uses: hendrikmuhs/ccache-action@main
      #  with:
      #    key: ${{ github.job }}-${matrix.os}-${{ matrix.arch }}-${{ matrix.py }}
      #
      #- uses: actions/cache@v3
      #  id: pyuwsgi-wheel
      #  name: cache wheel
      #  with:
      #    path: dist
      #    key: ${{ needs.build_sdist.outputs.sdist_name }}-${{ matrix.os }}-${{ matrix.arch }}

        #pyuwsgi-2.0.23.post0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
        #pyuwsgi-2.0.23.post0-cp312-cp312-macosx_11_0_arm64.whl

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.20.0
        with:
          output-dir: dist
          package-dir: ./${{ needs.build_sdist.outputs.sdist_name }}
        env:
          CIBW_BUILD: cp312-*
          CIBW_ARCHS: ${{ matrix.arch }}
          CIBW_SKIP: cp36-* cp38-macosx_arm64 pp* cp312-musllinux*
          CIBW_ENVIRONMENT: UWSGI_PROFILE=pikesquares
          CIBW_ENVIRONMENT_MACOS: LDFLAGS="-L/opt/homebrew/opt/openssl@1.3/lib" CPPFLAGS="-I/opt/homebrew/opt/openssl@1.3/include" PKG_CONFIG_PATH="/opt/homebrew/opt/openssl@1.3/lib/pkgconfig"
          CIBW_TEST_COMMAND: "pyuwsgi --help"
          CIBW_BEFORE_BUILD_MACOS: "find . -name '*.o' -delete && IS_MACOS=1 ./pre_build.sh"
          CIBW_BEFORE_BUILD_LINUX: "find . -name '*.o' -delete && ./pre_build.sh && (yum install -y zlib-devel openssl-devel zeromq-devel libsqlite3x-devel.x86_64 || apk add zlib-dev openssl-dev zeromq-dev sqlite-dev)"
          MACOSX_DEPLOYMENT_TARGET: 13.0
          CIBW_REPAIR_WHEEL_COMMAND_MACOS: "\
                  delocate-listdeps --depending {wheel} && \
                  delocate-wheel --require-archs {delocate_archs} -w {dest_dir} -vv {wheel}"

      - uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.os }}-${{ matrix.arch }}
          path: dist
  verify:
    name: Verify wheels
    runs-on: ubuntu-latest
    needs: [build_wheels]
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: dist-*
          path: dist
          merge-multiple: true
      - name: Verify sdist
        run: ls -lh dist/*.tar.gz
      - name: Verify wheels
        run: ls -lh dist/*.whl
  pypi-publish:
    #if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    needs: [verify]
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    #environment:
    #  name: pypi
    #  url: https://pypi.org/p/pyuwsgi
    permissions:
      id-token: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          pattern: dist-*
          path: dist
          merge-multiple: true
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          print-hash: true
          verbose: true
          user: ${{ secrets.PYPI_USER }}
          password: ${{ secrets.PYPI_PASSWORD }}
          repository-url: ${{ secrets.PYPI_REPO_URL }}
          packages-dir: dist
